a.out : EN10MainStates.o EN10States.o
	gcc EN10MainStates.o EN10States.o

EN10MainStates.o : EN10MainStates.c EN10States.h
	gcc EN10MainStates.c -c

EN10States.o : EN10States.c EN10States.h
	gcc EN10States.c -c